# not upstream: collision addon, cmake -P -DCOLL_SRC=<addon source> -DCOLL_WORK=<scratch> [-DCOLL_GEN= -DCOLL_MAKE= -DCOLL_CXX=]: a standalone configure finds rcresources.cmake and rc2cpp.py or stops naming them
cmake_minimum_required(VERSION 3.21)
file(REMOVE_RECURSE "${COLL_WORK}")
file(MAKE_DIRECTORY "${COLL_WORK}")
get_filename_component(rc "${COLL_SRC}/../../../cmake" ABSOLUTE)

function(fake_orbiter dir) # the SDK header and library the addon checks first; ARGN: the files its cmake/ holds
	file(WRITE "${dir}/Orbitersdk/include/OrbiterAPI.h" "// fake\n")
	file(WRITE "${dir}/Orbitersdk/lib/libOrbitersdk.a" "")
	foreach (f ${ARGN})
		file(COPY "${rc}/${f}" DESTINATION "${dir}/cmake")
	endforeach ()
endfunction()

function(configure src bin)
	set(args -S "${src}" -B "${bin}" -DCOLLISION_TESTS=OFF)
	if (COLL_GEN)
		list(APPEND args -G "${COLL_GEN}")
	endif ()
	if (COLL_MAKE)
		list(APPEND args "-DCMAKE_MAKE_PROGRAM=${COLL_MAKE}")
	endif ()
	if (COLL_CXX)
		list(APPEND args "-DCMAKE_CXX_COMPILER=${COLL_CXX}")
	endif ()
	execute_process(COMMAND ${CMAKE_COMMAND} ${args} ${ARGN} RESULT_VARIABLE r OUTPUT_VARIABLE o ERROR_VARIABLE e)
	set(res "${r}" PARENT_SCOPE)
	set(log "${o}${e}" PARENT_SCOPE)
endfunction()

function(expect name ok dir)
	if ((ok AND NOT res EQUAL 0) OR (NOT ok AND res EQUAL 0))
		message(SEND_ERROR "${name}: configure exit ${res}\n${log}")
		return ()
	endif ()
	string(FIND "${log}" "Collision: rcresources.cmake and rc2cpp.py from ${dir}\n" at)
	if (ok AND at LESS 0)
		message(SEND_ERROR "${name}: not taken from ${dir}\n${log}")
	else ()
		message(STATUS "pass: ${name}")
	endif ()
endfunction()

fake_orbiter("${COLL_WORK}/inst" rcresources.cmake rc2cpp.py) # an install: Orbitersdk/sample_build puts both into cmake/
fake_orbiter("${COLL_WORK}/tree") # a build tree: its cmake/ has neither
fake_orbiter("${COLL_WORK}/half" rcresources.cmake)

configure("${COLL_SRC}" "${COLL_WORK}/b1" "-DORBITER_DIR=${COLL_WORK}/tree")
expect("build tree: the source tree's cmake/" ON "${rc}")
configure("${COLL_SRC}" "${COLL_WORK}/b1" "-DORBITER_DIR=${COLL_WORK}/inst")
expect("install after a build tree: the stale cached ORBITER_CMAKE_DIR is passed over" ON "${COLL_WORK}/inst/cmake")
configure("${COLL_SRC}" "${COLL_WORK}/b1" "-DORBITER_DIR=${COLL_WORK}/inst" "-DORBITER_CMAKE_DIR=${rc}")
expect("ORBITER_CMAKE_DIR first" ON "${rc}")

file(COPY "${COLL_SRC}/CMakeLists.txt" DESTINATION "${COLL_WORK}/s/a/b/Collision") # no ../../../cmake around it
configure("${COLL_WORK}/s/a/b/Collision" "${COLL_WORK}/b2" "-DORBITER_DIR=${COLL_WORK}/half")
expect("rc2cpp.py missing" OFF "")
foreach (want "rcresources.cmake and rc2cpp.py not found together in ${COLL_WORK}/half/cmake, " "set ORBITER_CMAKE_DIR")
	string(REPLACE "\n" " " flat "${log}")
	string(REGEX REPLACE " +" " " flat "${flat}")
	string(FIND "${flat}" "${want}" at)
	if (at LESS 0)
		message(SEND_ERROR "FATAL_ERROR text lacks \"${want}\":\n${log}")
	endif ()
endforeach ()
