# not upstream: collision addon, cmake -P -DCOLL_CFG_SRC=<template> -DCOLL_CFG_DST=<Config/Collision.cfg>: copy if missing, else upgrade an older file in place
cmake_minimum_required(VERSION 3.21)
if (NOT COLL_CFG_SRC OR NOT COLL_CFG_DST)
	message(FATAL_ERROR "CollisionCfgOnce: COLL_CFG_SRC and COLL_CFG_DST are required")
endif ()

# the value of the first non-comment "key = value" line of a cfg text (keys case-insensitive, as the core); "" if none
function(coll_cfg_value text key out)
	string(TOUPPER "${key}" ukey)
	string(TOUPPER "${text}" utext)
	string(REGEX MATCH "(^|\n)[ \t]*${ukey}[ \t]*=[ \t]*([^\r\n;]*)" m "${utext}")
	string(STRIP "${CMAKE_MATCH_2}" v)
	set(${out} "${v}" PARENT_SCOPE)
endfunction()

file(READ "${COLL_CFG_SRC}" tpl)
coll_cfg_value("${tpl}" CollisionCfgVersion want)
if (NOT want MATCHES "^[0-9]+$")
	message(FATAL_ERROR "CollisionCfgOnce: ${COLL_CFG_SRC} has no CollisionCfgVersion")
endif ()

if (NOT EXISTS "${COLL_CFG_DST}")
	get_filename_component(dir "${COLL_CFG_DST}" DIRECTORY)
	file(MAKE_DIRECTORY "${dir}")
	file(COPY_FILE "${COLL_CFG_SRC}" "${COLL_CFG_DST}")
	return ()
endif ()

file(READ "${COLL_CFG_DST}" text) # text mode: CRLF files come back with LF
string(ASCII 239 187 191 bom)
string(SUBSTRING "${text}" 0 3 lead3)
if (lead3 STREQUAL bom) # a UTF-8 BOM: matched without it, written back with it
	string(SUBSTRING "${text}" 3 -1 text)
else ()
	set(bom "")
endif ()
coll_cfg_value("${text}" CollisionCfgVersion have)
if (NOT have MATCHES "^[0-9]+$")
	set(have 1) # v1 files had no version key
endif ()
if (have GREATER_EQUAL want)
	return ()
endif ()

# v1 -> v2: CollisionModel = 0 was the shipped default, now 1; a deliberate 0 in a v1 file cannot be told apart and is upgraded too (review R5)
if (have LESS 2)
	string(TOUPPER "${text}" utext)
	string(REGEX MATCH "(^|\n)([ \t]*COLLISIONMODEL[ \t]*=[ \t]*)([^\r\n;]*)" m "${utext}") # the first key line, the one the core reads
	string(LENGTH "${CMAKE_MATCH_1}${CMAKE_MATCH_2}" lead)
	string(STRIP "${CMAKE_MATCH_3}" v)
	if (m AND v STREQUAL "0")
		string(FIND "${utext}" "${m}" at)
		math(EXPR zero "${at} + ${lead}")
		math(EXPR rest "${zero} + 1")
		string(SUBSTRING "${text}" 0 ${zero} a)
		string(SUBSTRING "${text}" ${rest} -1 b)
		set(text "${a}1${b}")
		message(STATUS "Collision: ${COLL_CFG_DST}: CollisionModel = 0 of a version ${have} file set to 1, the new default")
	endif ()
endif ()

# the version line: replaced in place if present, else inserted after the first line when that is a comment, else at the top
string(TOUPPER "${text}" utext)
string(REGEX MATCH "(^|\n)([ \t]*COLLISIONCFGVERSION[ \t]*=)[^\r\n]*" m "${utext}")
if (m)
	string(LENGTH "${CMAKE_MATCH_1}" l1)
	string(LENGTH "${m}" lm)
	string(FIND "${utext}" "${m}" at)
	math(EXPR s "${at} + ${l1}")
	math(EXPR e "${at} + ${lm}")
	string(SUBSTRING "${text}" 0 ${s} a)
	string(SUBSTRING "${text}" ${e} -1 b)
	set(text "${a}CollisionCfgVersion = ${want}${b}")
else ()
	set(ins "; Version of this file's defaults; the build and install upgrade older files in place and keep every other line\nCollisionCfgVersion = ${want}\n")
	string(FIND "${text}" "\n" first)
	string(REGEX MATCH "^[ \t]*;" comment "${text}")
	if (comment AND first GREATER_EQUAL 0)
		math(EXPR cut "${first} + 1")
		string(SUBSTRING "${text}" 0 ${cut} a)
		string(SUBSTRING "${text}" ${cut} -1 b)
		set(text "${a}${ins}${b}")
	else ()
		set(text "${ins}${text}")
	endif ()
endif ()
file(WRITE "${COLL_CFG_DST}" "${bom}${text}")
message(STATUS "Collision: ${COLL_CFG_DST} upgraded from version ${have} to ${want}")
