# not upstream: collision addon, cmake -P -DCOLL_SRC=<addon source> -DCOLL_BUILD=<top build dir> -DCOLL_WORK=<scratch>: the install(CODE) cfg step copies, then keeps a user's file
cmake_minimum_required(VERSION 3.21)
file(REMOVE_RECURSE "${COLL_WORK}")
file(MAKE_DIRECTORY "${COLL_WORK}")
file(READ "${COLL_SRC}/Config/Collision.cfg" T)

function(install_once)
	execute_process(COMMAND ${CMAKE_COMMAND} -E env "DESTDIR=${COLL_WORK}/d" ${CMAKE_COMMAND} --install "${COLL_BUILD}" --prefix "${COLL_WORK}/p" --component Collision
		RESULT_VARIABLE r OUTPUT_VARIABLE o ERROR_VARIABLE e)
	if (NOT r EQUAL 0)
		message(FATAL_ERROR "install failed: ${o}${e}")
	endif ()
	file(GLOB_RECURSE cfg "${COLL_WORK}/d/Collision.cfg")
	list(FILTER cfg INCLUDE REGEX "/Config/Collision\\.cfg$")
	list(LENGTH cfg n)
	if (NOT n EQUAL 1)
		message(FATAL_ERROR "expected one installed Config/Collision.cfg, found ${n}: ${cfg}")
	endif ()
	set(cfg "${cfg}" PARENT_SCOPE)
endfunction()

install_once()
file(READ "${cfg}" got)
if (NOT got STREQUAL T)
	message(FATAL_ERROR "first install: ${cfg} is not the template")
endif ()
message(STATUS "pass: first install copies the template")
file(APPEND "${cfg}" "CollisionLog = 3 ; mine\n")
file(READ "${cfg}" mine)
install_once()
file(READ "${cfg}" got)
if (NOT got STREQUAL mine)
	message(FATAL_ERROR "second install changed the user's ${cfg}")
endif ()
message(STATUS "pass: second install keeps the user's file")
