# not upstream: collision addon, cmake -P -DCOLL_SRC=<addon source> -DCOLL_WORK=<scratch> -DGIT=<git>: win2024.cmake takes headers only from COLLISION_UPSTREAM_GIT or COLLISION_WIN2024_HEADERS, keyed by a stamp
cmake_minimum_required(VERSION 3.21)
file(REMOVE_RECURSE "${COLL_WORK}")
file(MAKE_DIRECTORY "${COLL_WORK}/p")
file(WRITE "${COLL_WORK}/p/CMakeLists.txt" "cmake_minimum_required(VERSION 3.21)\nproject(W NONE)\ninclude([[${COLL_SRC}/cmake/win2024.cmake]])\nmessage(STATUS \"W2024=[\${COLL_W2024_INCLUDE}]\")\n")
set(out "${COLL_WORK}/b/Win2024")

function(git dir)
	execute_process(COMMAND "${GIT}" -C "${dir}" -c user.name=t -c user.email=t@t -c commit.gpgsign=false ${ARGN} RESULT_VARIABLE r OUTPUT_VARIABLE o ERROR_VARIABLE e OUTPUT_STRIP_TRAILING_WHITESPACE)
	if (NOT r EQUAL 0)
		message(FATAL_ERROR "git ${ARGN} in ${dir}: ${e}")
	endif ()
	set(git_out "${o}" PARENT_SCOPE)
endfunction()

function(tag_sdk dir text) # a stand-in clone: Orbitersdk/include with Lua/lua.h at the tag 2024
	file(MAKE_DIRECTORY "${dir}")
	if (NOT EXISTS "${dir}/.git")
		git("${dir}" init -q)
	endif ()
	file(WRITE "${dir}/Orbitersdk/include/OrbiterAPI.h" "${text}")
	file(WRITE "${dir}/Orbitersdk/include/Lua/lua.h" "// lua\n")
	git("${dir}" add -A)
	git("${dir}" commit -q -m "${text}")
	git("${dir}" tag -f 2024)
	git("${dir}" rev-parse HEAD)
	set(commit "${git_out}" PARENT_SCOPE)
endfunction()

function(configure)
	execute_process(COMMAND ${CMAKE_COMMAND} -E env "HOME=${COLL_WORK}/home" ${CMAKE_COMMAND} -S "${COLL_WORK}/p" -B "${COLL_WORK}/b" ${ARGN}
		RESULT_VARIABLE r OUTPUT_VARIABLE o ERROR_VARIABLE e)
	if (NOT r EQUAL 0)
		message(FATAL_ERROR "configure failed: ${o}${e}")
	endif ()
	string(REGEX MATCH "W2024=\\[([^]]*)\\]" m "${o}")
	set(inc "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()

function(expect name want_inc want_api)
	set(api "")
	if (EXISTS "${out}/include/OrbiterAPI.h")
		file(READ "${out}/include/OrbiterAPI.h" api)
	endif ()
	if (NOT inc STREQUAL want_inc OR NOT api STREQUAL want_api)
		message(SEND_ERROR "${name}: headers [${inc}] with OrbiterAPI.h [${api}], expected [${want_inc}] with [${want_api}]")
	else ()
		message(STATUS "pass: ${name}")
	endif ()
endfunction()

tag_sdk("${COLL_WORK}/home/orbiter" "// home\n") # ~/orbiter at the tag: never a source any more
tag_sdk("${COLL_WORK}/up" "// up 1\n")
set(c1 "${commit}")

configure("-DCOLLISION_UPSTREAM_GIT=" "-DCOLLISION_WIN2024_HEADERS=")
expect("no source set, ~/orbiter ignored" "" "")
file(WRITE "${out}/include/OrbiterAPI.h" "// home\n") # a tree configured before the stamp, with headers taken from ~/orbiter
file(WRITE "${out}/include/lua/lua.h" "// lua\n")
configure()
expect("an unstamped extraction is removed" "" "")
file(WRITE "${out}/include/OrbiterAPI.h" "// home\n")
file(WRITE "${out}/include/lua/lua.h" "// lua\n")
configure("-DCOLLISION_UPSTREAM_GIT=${COLL_WORK}/up")
expect("the clone replaces an unstamped extraction" "${out}/include" "// up 1\n")
file(READ "${out}/stamp.txt" s)
if (NOT s STREQUAL "${COLL_WORK}/up ${c1}")
	message(SEND_ERROR "stamp [${s}], expected [${COLL_WORK}/up ${c1}]")
endif ()
configure()
expect("same tag: kept" "${out}/include" "// up 1\n")
tag_sdk("${COLL_WORK}/up" "// up 2\n")
configure()
expect("the tag moved: extracted again" "${out}/include" "// up 2\n")
configure("-DCOLLISION_UPSTREAM_GIT=")
expect("source unset: the extraction is removed" "" "")
if (EXISTS "${out}")
	message(SEND_ERROR "${out} left behind")
endif ()
file(WRITE "${COLL_WORK}/hdr/OrbiterAPI.h" "// hdr\n")
file(WRITE "${COLL_WORK}/hdr/lua/lua.h" "// lua\n")
configure("-DCOLLISION_WIN2024_HEADERS=${COLL_WORK}/hdr" "-DCOLLISION_UPSTREAM_GIT=${COLL_WORK}/up")
expect("COLLISION_WIN2024_HEADERS first" "${COLL_WORK}/hdr" "")
