# not upstream: Phase D unit tests (E3-U1 to E3-U15)
coll_unit_test(CollStore.Test 30 UNITS CollStore DentMath Vecmat)
if (TARGET Coll_CollDamageA)
	coll_unit_test(CollDamageA.Test 120 UNITS CollDamageA CollVisualA CollStore CollApiA CollSdk CollShape CollAnim CollGeom DentMath CollCfg Vecmat)
endif ()
