# not upstream: collision addon, finds the Orbiter 2024 SDK headers for Collision.Win2024.Compile; sets COLL_W2024_INCLUDE or leaves it empty
set(COLLISION_WIN2024_HEADERS "" CACHE PATH "Orbiter 2024 Orbitersdk/include with lua/lua.h; empty: taken from COLLISION_UPSTREAM_GIT")
set(COLLISION_UPSTREAM_GIT "" CACHE PATH "A clone of orbitersim/orbiter with the tag 2024; empty: ~/orbiter if it has the tag")
set(COLL_W2024_INCLUDE "")
if (COLLISION_WIN2024_HEADERS)
	set(COLL_W2024_INCLUDE ${COLLISION_WIN2024_HEADERS})
else ()
	find_package(Git QUIET)
	set(repo ${COLLISION_UPSTREAM_GIT})
	if (NOT repo AND EXISTS "$ENV{HOME}/orbiter/.git")
		set(repo "$ENV{HOME}/orbiter")
	endif ()
	set(out ${CMAKE_CURRENT_BINARY_DIR}/Win2024)
	if (repo AND GIT_FOUND AND NOT EXISTS ${out}/include/lua/lua.h)
		execute_process(COMMAND ${GIT_EXECUTABLE} -C ${repo} rev-parse --verify -q "2024^{commit}" RESULT_VARIABLE r OUTPUT_QUIET ERROR_QUIET)
		if (r EQUAL 0) # read only: git archive of the tag, nothing in the clone changes
			file(REMOVE_RECURSE ${out})
			file(MAKE_DIRECTORY ${out})
			execute_process(COMMAND ${GIT_EXECUTABLE} -C ${repo} archive --format=tar -o ${out}/sdk.tar 2024 Orbitersdk/include RESULT_VARIABLE r)
			if (r EQUAL 0)
				file(ARCHIVE_EXTRACT INPUT ${out}/sdk.tar DESTINATION ${out}/x)
				file(RENAME ${out}/x/Orbitersdk/include ${out}/include)
				if (EXISTS ${out}/include/Lua AND NOT EXISTS ${out}/include/lua)
					file(RENAME ${out}/include/Lua ${out}/include/lua) # OrbiterAPI.h includes <lua/lua.h>; the tag holds Lua/
				endif ()
			endif ()
			file(REMOVE_RECURSE ${out}/x ${out}/sdk.tar)
		endif ()
	endif ()
	if (EXISTS ${out}/include/lua/lua.h)
		set(COLL_W2024_INCLUDE ${out}/include)
	endif ()
endif ()
if (COLL_W2024_INCLUDE AND NOT (EXISTS ${COLL_W2024_INCLUDE}/OrbiterAPI.h AND EXISTS ${COLL_W2024_INCLUDE}/lua/lua.h))
	message(WARNING "Collision: ${COLL_W2024_INCLUDE} has no OrbiterAPI.h and lua/lua.h; Collision.Win2024.Compile not registered")
	set(COLL_W2024_INCLUDE "")
endif ()
if (COLL_W2024_INCLUDE)
	message(STATUS "Collision: Orbiter 2024 headers for Collision.Win2024.Compile: ${COLL_W2024_INCLUDE}")
else ()
	message(STATUS "Collision: no Orbiter 2024 headers (COLLISION_WIN2024_HEADERS, COLLISION_UPSTREAM_GIT); Collision.Win2024.Compile not registered")
endif ()
