# cmake -DLIBRARY=<XRSound.so> -DREADELF=.. -DNM=.. -P CheckNoPipeWireLink.cmake: no libpipewire in NEEDED, pw_ imports or the ldd tree
execute_process(COMMAND ${READELF} -d ${LIBRARY} OUTPUT_VARIABLE dynamic RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
	message(FATAL_ERROR "readelf -d ${LIBRARY} failed")
endif()
if(dynamic MATCHES "libpipewire")
	message(FATAL_ERROR "${LIBRARY} has libpipewire in NEEDED")
endif()
execute_process(COMMAND ${NM} -D --undefined-only ${LIBRARY} OUTPUT_VARIABLE undefined RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
	message(FATAL_ERROR "nm -D ${LIBRARY} failed")
endif()
if(undefined MATCHES "[ \t]pw_")
	message(FATAL_ERROR "${LIBRARY} imports pw_ symbols")
endif()
execute_process(COMMAND ldd ${LIBRARY} OUTPUT_VARIABLE tree RESULT_VARIABLE rc)
if(tree MATCHES "libpipewire")
	message(FATAL_ERROR "${LIBRARY} pulls libpipewire in through a dependency")
endif()
message(STATUS "${LIBRARY}: no libpipewire dependency")
