# not upstream: generated scenarios of the collision addon scenario tests (Design CA E4 7.4-7.5, design-C-T 4.7, 7.2)
import math
import os
import re

GGRAV = 6.67259e-11  # OrbiterAPI.h
PLANETS = {'Earth': (5.973698968e+24, 6.37101e6), 'Moon': (7.347673176382784e+22, 1.738e6)}  # Config Mass, Size
MJD = 51982.5
R_P0 = 6778137.0
TESTCLASSES = ('CollTestVessel', 'CollTestDirector', 'CollTestAnim', 'CollTestAnimVC')


def g(x):
    return '%.17g' % x


def v_circ(planet, r):
    m, _ = PLANETS[planet]
    return math.sqrt(GGRAV * m / r)


def head(focus, desc, planet='Earth'):
    return ('BEGIN_DESC\nnot upstream: generated by gen_scn.py (%s)\nEND_DESC\n\n' % desc
            + 'BEGIN_ENVIRONMENT\n  System Sol\n  Date MJD %s\nEND_ENVIRONMENT\n\n' % g(MJD)
            + 'BEGIN_FOCUS\n  Ship %s\nEND_FOCUS\n\n' % focus
            + 'BEGIN_CAMERA\n  TARGET %s\n  MODE Extern\n  POS 4.00 20.00 10.00\n  TRACKMODE TargetRelative\n  FOV 40.00\nEND_CAMERA\n\n' % focus
            + 'BEGIN_SHIPS\n')


def director(planet='Earth', name='TD'):  # mesh-less, no collider, twice the planet radius (T 4.6)
    _, rad = PLANETS[planet]
    r = 2 * rad
    return ('%s:CollTestDirector\n  STATUS Orbiting %s\n  RPOS %s 0 0\n  RVEL 0 0 %s\n  AROT 0 0 0\nEND\n'
            % (name, planet, g(r), g(v_circ(planet, r))))


def pair(p):  # P0 LEO pair (T 7.2): A at the P0 orbit, B 6 m + g0 ahead along z, noses facing
    g0, va, vb = float(p.get('g0', 1000)), float(p.get('vA', 0)), float(p.get('vB', 0))
    x = float(p.get('x', 0))
    ca, cb = p.get('A', 'ShuttlePB'), p.get('B', 'ShuttlePB')
    v0 = v_circ('Earth', R_P0)
    s = head('PB-A', 'P0 pair g0=%s vA=%s vB=%s' % (g0, va, vb))
    if p.get('director') == '1':
        s += director('Earth')
    s += 'PB-A:%s\n  STATUS Orbiting Earth\n  RPOS %s 0 0\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0\nEND\n' % (ca, g(R_P0), g(v0 + va))
    s += 'PB-B:%s\n  STATUS Orbiting Earth\n  RPOS %s 0 %s\n  RVEL 0 0 %s\n  AROT 0 180 0\n  PRPLEVEL 0:0\nEND\n' % (cb, g(R_P0 + x), g(6.0 + g0), g(v0 + vb))
    return s + 'END_SHIPS\n'


def surface(p):  # BB: DG landed on pad 1, ShuttlePB landed on pad 2 (G4)
    s = head('GL', 'Brighton Beach surface pair', 'Moon')
    if p.get('director') == '1':
        s += director('Moon')
    rc = '  RCOVER 1.0000 0.0000\n' if p.get('rcover') == '1' else ''  # retro covers open and at rest: state, speed (AnimState2, Instrument.cpp:242-260)
    s += 'GL:DeltaGlider\n  STATUS Landed Moon\n  BASE Brighton Beach:1\n  HEADING 0.00\n  PRPLEVEL 0:0.5 1:1\n  NOSECONE 0 0.0000\n  GEAR 1 1.0000\n%sEND\n' % rc
    s += 'PB:ShuttlePB\n  STATUS Landed Moon\n  BASE Brighton Beach:2\n  HEADING 90.00\n  PRPLEVEL 0:0\nEND\n'
    return s + 'END_SHIPS\n'


def ascent(p, args):  # G3: Demo/Atlantis Ascent AP with the autopilot engaged by its scenario state, liftoff at simt 4 s (AscentAP.cpp:81-91, :537-551)
    path = os.path.join(args.root, 'Scenarios', 'Demo', 'Atlantis Ascent AP.scn')  # its script's Shift-key MFD presses crash headless: no pane (Orbiter.cpp:2402)
    text = open(path, encoding='latin-1').read()
    text = re.sub(r'(?m)^(\s*)ASCENTAP 0 0 (.*)$', r'\1ASCENTAP 1 1 \2', text)
    text = re.sub(r'(?m)^(\s*)MET 0\.000 0\.000 0\.000 0\.000$', r'\1MET -4.000 -1.000 -1.000 -1.000', text)
    if 'ASCENTAP 1 1 ' not in text or 'MET -4.000' not in text:
        raise ValueError('Atlantis Ascent AP.scn changed: ASCENTAP or MET line not found')
    return set_script(text, None)[0]


GENERATORS = {'pair': pair, 'surface': surface, 'ascent': ascent}


def params(text):
    out = {}
    for t in text.split(','):
        if '=' in t:
            k, v = t.split('=', 1)
            out[k.strip()] = v.strip()
    return out


def generate(spec, args=None):  # "name" or "name:k=v,k=v"
    name, _, rest = spec.partition(':')
    if name not in GENERATORS:
        raise ValueError('unknown generated scenario %r' % name)
    fn = GENERATORS[name]
    return fn(params(rest), args) if fn.__code__.co_argcount == 2 else fn(params(rest))


def set_script(text, script):  # replaces the scenario's Script line (None: removes it); returns the text and the old script
    lines = text.splitlines()
    orig, out, inenv, done = None, [], False, False
    for l in lines:
        s = l.strip()
        if s.upper() == 'BEGIN_ENVIRONMENT':
            inenv = True
            done = True
        elif inenv and s.upper() == 'END_ENVIRONMENT':
            if script:
                out.append('  Script %s' % script)
            inenv = False
        elif inenv and re.match(r'(?i)^script\b', s):
            orig = s[6:].strip()
            continue
        out.append(l)
    if not done:
        raise ValueError('scenario has no BEGIN_ENVIRONMENT block')
    return '\n'.join(out) + '\n', orig


def ship_planet(text):
    m = re.search(r'(?im)^\s*STATUS\s+\S+\s+(\S+)', text)
    return m.group(1) if m and m.group(1) in PLANETS else 'Earth'


def insert_actions(text, actions):  # into the first test-module block, else a director listed first (E4 7.4); "@<ship>:<line>" goes into that ship's block
    own = {}
    for a in actions:
        if a.startswith('@') and ':' in a:
            n, l = a[1:].split(':', 1)
            own.setdefault(n, []).append(l.strip())
    actions = [a for a in actions if not (a.startswith('@') and ':' in a)]
    lines = text.splitlines()
    out, inships, inblock, name, done = [], False, None, None, not actions
    for l in lines:
        s = l.strip()
        if s.upper() == 'BEGIN_SHIPS':
            inships = True
        elif inships and s.upper() == 'END_SHIPS':
            inships = False
        elif inships and inblock is None and s and s.upper() != 'END':
            name, inblock = (s.split(':', 1)[0].strip(), s.split(':', 1)[1].strip()) if ':' in s else (s, s)
        elif inships and inblock is not None and s.upper() == 'END':
            out += ['  ' + a for a in own.pop(name, [])]
            if inblock in TESTCLASSES and not done:
                out += ['  ' + a for a in actions]
                done = True
            inblock = None
        out.append(l)
    if own:
        raise ValueError('no ship block for %s' % ', '.join(sorted(own)))
    if not done:
        i = next((n for n, l in enumerate(out) if l.strip().upper() == 'BEGIN_SHIPS'), None)
        if i is None:
            raise ValueError('scenario has no BEGIN_SHIPS block')
        d = director(ship_planet(text)).rstrip('\n').split('\n')
        out[i + 1:i + 1] = d[:-1] + ['  ' + a for a in actions] + ['END']
    return '\n'.join(out) + '\n'
