# not upstream: generated scenarios of the collision addon scenario tests (Design CA E4 7.4-7.5, design-C-T 4.7, 7.2)
import math
import os
import re

GGRAV = 6.67259e-11  # OrbiterAPI.h
PLANETS = {'Earth': (5.973698968e+24, 6.37101e6), 'Moon': (7.347673176382784e+22, 1.738e6)}  # Config Mass, Size
MJD = 51982.5
R_P0 = 6778137.0
TESTCLASSES = ('CollTestVessel', 'CollTestDirector', 'CollTestAnim', 'CollTestAnimVC')
ACTCLASSES = ('CollTestVessel', 'CollTestDirector')  # the classes that run TEST* actions; CollTestAnim blocks drop them


def g(x):
    return '%.17g' % x


def v_circ(planet, r):
    m, _ = PLANETS[planet]
    return math.sqrt(GGRAV * m / r)


def head(focus, desc, planet='Earth'):
    return ('BEGIN_DESC\nnot upstream: generated by gen_scn.py (%s)\nEND_DESC\n\n' % desc
            + 'BEGIN_ENVIRONMENT\n  System Sol\n  Date MJD %s\nEND_ENVIRONMENT\n\n' % g(MJD)
            + 'BEGIN_FOCUS\n  Ship %s\nEND_FOCUS\n\n' % focus
            + 'BEGIN_CAMERA\n  TARGET %s\n  MODE Extern\n  POS 4.00 20.00 10.00\n  TRACKMODE TargetRelative\n  FOV 40.00\nEND_CAMERA\n\n' % focus
            + 'BEGIN_SHIPS\n')


BLOCKS = {'destroyed': ('\nBEGIN_Collision\nCOLLA 1\nVESSEL 0 PB-A ShuttlePB\nXDMG 1 500000 0\nEND_VESSEL\nEND\n')}  # addon blocks (E3 7.8 syntax)


def director(planet='Earth', name='TD'):  # mesh-less, no collider, twice the planet radius (T 4.6)
    _, rad = PLANETS[planet]
    r = 2 * rad
    return ('%s:CollTestDirector\n  STATUS Orbiting %s\n  RPOS %s 0 0\n  RVEL 0 0 %s\n  AROT 0 0 0\nEND\n'
            % (name, planet, g(r), g(v_circ(planet, r))))


def pair(p):  # P0 LEO pair (T 7.2): A at the P0 orbit, B 6 m + g0 ahead along z, noses facing
    g0, va, vb = float(p.get('g0', 1000)), float(p.get('vA', 0)), float(p.get('vB', 0))
    x = float(p.get('x', 0))
    ca, cb = p.get('A', 'ShuttlePB'), p.get('B', 'ShuttlePB')
    v0 = v_circ('Earth', R_P0)
    s = head('PB-A', 'P0 pair g0=%s vA=%s vB=%s' % (g0, va, vb))
    if p.get('director') == '1':
        s += director('Earth')
    s += 'PB-A:%s\n  STATUS Orbiting Earth\n  RPOS %s 0 0\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0\nEND\n' % (ca, g(R_P0), g(v0 + va))
    s += 'PB-B:%s\n  STATUS Orbiting Earth\n  RPOS %s 0 %s\n  RVEL 0 0 %s\n  AROT 0 180 0\n  PRPLEVEL 0:0\nEND\n' % (cb, g(R_P0 + x), g(6.0 + g0), g(v0 + vb))
    return s + 'END_SHIPS\n' + BLOCKS.get(p.get('block', ''), '')


def surface(p):  # BB: DG landed on pad 1, ShuttlePB landed on pad 2 (G4)
    s = head('GL', 'Brighton Beach surface pair', 'Moon')
    if p.get('director') == '1':
        s += director('Moon')
    rc = '  RCOVER 1.0000 0.0000\n' if p.get('rcover') == '1' else ''  # retro covers open and at rest: state, speed (AnimState2, Instrument.cpp:242-260)
    s += 'GL:DeltaGlider\n  STATUS Landed Moon\n  BASE Brighton Beach:1\n  HEADING 0.00\n  PRPLEVEL 0:0.5 1:1\n  NOSECONE 0 0.0000\n  GEAR 1 1.0000\n%sEND\n' % rc
    s += 'PB:ShuttlePB\n  STATUS Landed Moon\n  BASE Brighton Beach:2\n  HEADING 90.00\n  PRPLEVEL 0:0\nEND\n'
    return s + 'END_SHIPS\n'


def ascent(p, args):  # G3: Demo/Atlantis Ascent AP with the autopilot engaged by its scenario state, liftoff at simt 4 s (AscentAP.cpp:81-91, :537-551)
    path = os.path.join(args.root, 'Scenarios', 'Demo', 'Atlantis Ascent AP.scn')  # its script's Shift-key MFD presses crash headless: no pane (Orbiter.cpp:2402)
    text = open(path, encoding='latin-1').read()
    text = re.sub(r'(?m)^(\s*)ASCENTAP 0 0 (.*)$', r'\1ASCENTAP 1 1 \2', text)
    text = re.sub(r'(?m)^(\s*)MET 0\.000 0\.000 0\.000 0\.000$', r'\1MET -4.000 -1.000 -1.000 -1.000', text)
    if 'ASCENTAP 1 1 ' not in text or 'MET -4.000' not in text:
        raise ValueError('Atlantis Ascent AP.scn changed: ASCENTAP or MET line not found')
    return set_script(text, None)[0]


def orbit(t, r, theta0):  # the circular P0 orbit in the ecliptic frame of Earth: position and velocity at simt t
    v = v_circ('Earth', r)
    th = theta0 + v / r * t
    return (r * math.cos(th), 0.0, r * math.sin(th)), (-v * math.sin(th), 0.0, v * math.cos(th))


def synthplay(p, args):  # a live PB-A and a PB-B played back from synthetic records along the P0 orbit 1 km ahead (E4 7.5 step 6, T0.8)
    stem = re.sub(r'[^A-Za-z0-9]+', '_', args.name).strip('_')
    th0 = 1006.0 / R_P0
    dur = args.frames * args.step + 5
    pos, att = ['STARTMJD %s' % g(MJD), 'REF Earth', 'FRM ECLIPTIC', 'CRD CARTESIAN'], ['STARTMJD %s' % g(MJD), 'FRM ECLIPTIC', 'REF Earth']
    t = 0.0
    while t <= dur:
        x, v = orbit(t, R_P0, th0)
        pos.append('%s %s %s %s %s %s %s' % (g(t), g(x[0]), g(x[1]), g(x[2]), g(v[0]), g(v[1]), g(v[2])))
        att.append('%s 0 %s 0' % (g(t), g(math.pi)))
        t += 1.0
    x, v = orbit(0.0, R_P0, th0)
    s = head('PB-A', 'synthetic playback: PB-B from Flights/%s' % stem)
    s += 'PB-A:ShuttlePB\n  STATUS Orbiting Earth\n  RPOS %s 0 0\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0\nEND\n' % (g(R_P0), g(v_circ('Earth', R_P0)))
    s += 'PB-B:ShuttlePB\n  STATUS Orbiting Earth\n  RPOS %s %s %s\n  RVEL %s %s %s\n  AROT 0 180 0\n  PRPLEVEL 0:0\n  FLIGHTDATA\nEND\nEND_SHIPS\n' % (
        g(x[0]), g(x[1]), g(x[2]), g(v[0]), g(v[1]), g(v[2]))
    return s, {'Flights/%s/PB-B.pos' % stem: '\n'.join(pos) + '\n', 'Flights/%s/PB-B.att' % stem: '\n'.join(att) + '\n'}


def hvc(p):  # Coll.HvC.Stock (T 4.5, T0.5): the P0 pair 1 km apart, ISS 3 km ahead and a DG 150 m behind it closing at 0.1 m/s; no contact, no clbkAnimate
    v0 = v_circ('Earth', R_P0)
    s = head('PB-A', 'headless vs client: P0 pair, ISS, DG approach') + director('Earth')
    s += 'PB-A:ShuttlePB\n  STATUS Orbiting Earth\n  RPOS %s 0 0\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0\nEND\n' % (g(R_P0), g(v0))
    s += 'PB-B:ShuttlePB\n  STATUS Orbiting Earth\n  RPOS %s 0 1006\n  RVEL 0 0 %s\n  AROT 0 180 0\n  PRPLEVEL 0:0\nEND\n' % (g(R_P0), g(v0))
    s += 'ISS:ProjectAlpha_ISS\n  STATUS Orbiting Earth\n  RPOS %s 0 4000\n  RVEL 0 0 %s\n  AROT 0 0 0\nEND\n' % (g(R_P0), g(v0))
    s += 'GL:DeltaGlider\n  STATUS Orbiting Earth\n  RPOS %s 0 3850\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0.5 1:1\nEND\n' % (g(R_P0), g(v0 + 0.1))
    return s + 'END_SHIPS\n'


def ksc(p):  # Coll.Base.KSC: CollTestVessels landed on Cape Canaveral pads 3-5, placed in frame 1 next to the HANGAR at base-local (7180, 0, -2180)
    s = head('PE', 'Cape Canaveral hangar neighbours')
    y = float(p.get('y', 1.55))  # touchdown points 1.5 m below the CG
    acts = ['TESTPLACEBASE 1 PE Cape_Canaveral 7180 %s -2160 0 0 0 0' % g(y),  # 2.4 m east of the east wall, wings along the wall normal
            'TESTPLACEBASE 1 PW Cape_Canaveral 7180 %s -2200 0 0 0 0' % g(y),  # 2.4 m west of the west wall
            'TESTPLACEBASE 1 PM Cape_Canaveral 7163 %s -2195 0 0 0.5 90' % g(y)]  # 2.4 m north of the north wall, 0.5 m/s east along it
    for n, pad in (('PE', 3), ('PW', 4), ('PM', 5)):
        s += '%s:CollTestVessel\n  STATUS Landed Earth\n  BASE Cape Canaveral:%d\n  HEADING 0.00\n  PRPLEVEL 0:0\n' % (n, pad)
        if n == 'PE':
            s += ''.join('  %s\n' % a for a in acts)
        s += 'END\n'
    return s + 'END_SHIPS\n'


def stack(p):  # Coll.Stack.Hit: PB-B docked onto PB-A in frame 1 (ports at y 1.3), TC nose to PB-A's nose 6 + g0 m apart closing at u in frame 3
    g0, u = float(p.get('g0', 0.12)), float(p.get('u', 0.015))
    v0 = v_circ('Earth', R_P0)
    s = head('PB-A', 'docked stack hit nose to nose g0=%s u=%s' % (g0, u))
    s += 'PB-A:CollTestVessel\n  STATUS Orbiting Earth\n  RPOS %s 0 0\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0\n' % (g(R_P0), g(v0))
    s += '  TESTDOCK 1 PB-A 0 PB-B 0 1\n  TESTPLACEREL 3 TC PB-A 0 0 %s 0 0 %s 0 180 0\nEND\n' % (g(6.0 + g0), g(-u))
    s += 'PB-B:CollTestVessel\n  STATUS Orbiting Earth\n  RPOS %s 0 60\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0\nEND\n' % (g(R_P0), g(v0))
    s += 'TC:CollTestVessel\n  STATUS Orbiting Earth\n  RPOS %s 0 -120\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0\nEND\n' % (g(R_P0), g(v0))
    return s + 'END_SHIPS\n'


def attached(p):  # Coll.Stack.Attached: PL attached on top of PB-A (CollTestVessel points), TC onto PL's nose closing at u in frame 3
    g0, u = float(p.get('g0', 0.12)), float(p.get('u', 0.1))
    v0 = v_circ('Earth', R_P0)
    s = head('PB-A', 'attached payload hit nose to nose g0=%s u=%s' % (g0, u))
    s += 'PB-A:CollTestVessel\n  STATUS Orbiting Earth\n  RPOS %s 0 0\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0\n' % (g(R_P0), g(v0))
    s += '  TESTPLACEREL 3 TC PB-A 0 3.8 %s 0 0 %s 0 180 0\nEND\n' % (g(6.0 + g0), g(-u))  # PL's CG 3.8 m above PB-A's (attachment points)
    s += 'PL:CollTestVessel\n  STATUS Orbiting Earth\n  RPOS %s 3.8 0\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0\n  ATTACHED 0:0,PB-A\nEND\n' % (g(R_P0), g(v0))
    s += 'TC:CollTestVessel\n  STATUS Orbiting Earth\n  RPOS %s 0 -120\n  RVEL 0 0 %s\n  AROT 0 0 0\n  PRPLEVEL 0:0\nEND\n' % (g(R_P0), g(v0))
    return s + 'END_SHIPS\n'


def wake(p):  # Coll.Landed.Wake: LP landed on Brighton Beach pad 2 (heading 90), HT placed in frame 1 east of it, nose to nose, closing at u
    u, g0, dy = float(p.get('u', 1.0)), float(p.get('g0', 0.1)), float(p.get('dy', 0.2))
    s = head('LP', 'landed partner hit at u=%s' % u, 'Moon')
    s += 'LP:CollTestVessel\n  STATUS Landed Moon\n  BASE Brighton Beach:2\n  HEADING 90.00\n  PRPLEVEL 0:0\n  TESTLOGMSG 1\n'
    s += '  TESTPLACEBASE 1 HT Brighton_Beach 100 %s %s 0 0 %s 270\nEND\n' % (g(1.5 + dy), g(-173.21 + 6.0 + g0), g(-u))
    s += 'HT:CollTestVessel\n  STATUS Landed Moon\n  BASE Brighton Beach:1\n  HEADING 0.00\n  PRPLEVEL 0:0\n  TESTLOGMSG 1\nEND\n'
    return s + 'END_SHIPS\n'


def hangar(p):  # Coll.Base.Hangar: a CollTestVessel placed in frame 1 where Coll.Base.KSC's PE rests, sliding west into the HANGAR's east wall at u m/s
    s = head('HB', 'Cape Canaveral hangar impact')
    y, u = float(p.get('y', 1.55)), float(p.get('u', 8.0))
    s += 'HB:CollTestVessel\n  STATUS Landed Earth\n  BASE Cape Canaveral:3\n  HEADING 0.00\n  PRPLEVEL 0:0\n'
    s += '  TESTPLACEBASE 1 HB Cape_Canaveral 7180 %s -2160 0 0 %s 0\nEND\n' % (g(y), g(-u))
    return s + 'END_SHIPS\n'


GENERATORS = {'pair': pair, 'surface': surface, 'ascent': ascent, 'synthplay': synthplay, 'hvc': hvc, 'ksc': ksc, 'hangar': hangar, 'stack': stack, 'attached': attached,
              'wake': wake}


def params(text):
    out = {}
    for t in text.split(','):
        if '=' in t:
            k, v = t.split('=', 1)
            out[k.strip()] = v.strip()
    return out


def generate(spec, args=None):  # "name" or "name:k=v,k=v"
    name, _, rest = spec.partition(':')
    if name not in GENERATORS:
        raise ValueError('unknown generated scenario %r' % name)
    fn = GENERATORS[name]
    return fn(params(rest), args) if fn.__code__.co_argcount == 2 else fn(params(rest))


def set_script(text, script):  # replaces the scenario's Script line (None: removes it); returns the text and the old script
    lines = text.splitlines()
    orig, out, inenv, done = None, [], False, False
    for l in lines:
        s = l.strip()
        if s.upper() == 'BEGIN_ENVIRONMENT':
            inenv = True
            done = True
        elif inenv and s.upper() == 'END_ENVIRONMENT':
            if script:
                out.append('  Script %s' % script)
            inenv = False
        elif inenv and re.match(r'(?i)^script\b', s):
            orig = s[6:].strip()
            continue
        out.append(l)
    if not done:
        raise ValueError('scenario has no BEGIN_ENVIRONMENT block')
    return '\n'.join(out) + '\n', orig


def ship_planet(text):
    m = re.search(r'(?im)^\s*STATUS\s+\S+\s+(\S+)', text)
    return m.group(1) if m and m.group(1) in PLANETS else 'Earth'


def insert_actions(text, actions):  # into the first test-module block, else a director listed first (E4 7.4); "@<ship>:<line>" goes into that ship's block
    own = {}
    for a in actions:
        if a.startswith('@') and ':' in a:
            n, l = a[1:].split(':', 1)
            own.setdefault(n, []).append(l.strip())
    actions = [a for a in actions if not (a.startswith('@') and ':' in a)]
    lines = text.splitlines()
    out, inships, inblock, name, done = [], False, None, None, not actions
    for l in lines:
        s = l.strip()
        if s.upper() == 'BEGIN_SHIPS':
            inships = True
        elif inships and s.upper() == 'END_SHIPS':
            inships = False
        elif inships and inblock is None and s and s.upper() != 'END':
            name, inblock = (s.split(':', 1)[0].strip(), s.split(':', 1)[1].strip()) if ':' in s else (s, s)
        elif inships and inblock is not None and s.upper() == 'END':
            out += ['  ' + a for a in own.pop(name, [])]  # by name: a CollTestAnim reads its own keys (TESTANIMCYCLE)
            if inblock in ACTCLASSES and not done:
                out += ['  ' + a for a in actions]
                done = True
            inblock = None
        out.append(l)
    if own:
        raise ValueError('no ship block for %s' % ', '.join(sorted(own)))
    if not done:
        i = next((n for n, l in enumerate(out) if l.strip().upper() == 'BEGIN_SHIPS'), None)
        if i is None:
            raise ValueError('scenario has no BEGIN_SHIPS block')
        d = director(ship_planet(text)).rstrip('\n').split('\n')
        out[i + 1:i + 1] = d[:-1] + ['  ' + a for a in actions] + ['END']
    return '\n'.join(out) + '\n'
